### ISSUE TITLE
Not working with ESP32 DEV (TTGO T7) and Teensy 3.1

### ISSUE THREAD

**Issue by kami83** [NachtRaveVL/Lepton-FLiR-Arduino#11] opened 2021-04-23 07:54 UTC
Hi,

i am now trying to use this library with  ESP32 DEV (TTGO T7) and Teensy 3.1 i used the wiring from the description and i only get with Debug the module infos. So i think the I2C is okay.

If i am trying to use the Advancedexample i get only to debug errors:

LeptonFLiR::readNextFrame AGC-8bit: disabled, Telemetry: enabled, Location: footer
LeptonFLiR::readNextFrame Maximum resync retries reached. Aborting.

LeptonFLiR::readNextFrame AGC-8bit: disabled, Telemetry: enabled, Location: footer
LeptonFLiR::readNextFrame Maximum frame skip reached. Aborting.

The second error is only when i am using the Teensy. I tried for the Teensy 96 Mhz, 72 and 48. 

Same problem.

Maybe some one can help or give me another Sketch example for the Teensy.

Thanks a lot.

Cu kami

**Comment by NachtRaveVL** [comment] 2021-04-24 04:38
Duplicate of #8 

There's a lot of 3.5 methods still to write out and even get anywhere near working, so won't be getting to this anytime soon.

**Closed as completed by NachtRaveVL** 2021-04-24 04:38 UTC
